name: admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.4.0
  file_picker: ^10.1.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
